//! DWARF type definitions and constants.
//!
//! This module defines the constants and types used in DWARF debugging information.
//! Reference: DWARF Version 5 Standard (<http://dwarfstd.org/>)

/// DWARF tag values (DW_TAG_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum DwTag {
    ArrayType = 0x01,
    ClassType = 0x02,
    EntryPoint = 0x03,
    EnumerationType = 0x04,
    FormalParameter = 0x05,
    ImportedDeclaration = 0x08,
    Label = 0x0A,
    LexicalBlock = 0x0B,
    Member = 0x0D,
    PointerType = 0x0F,
    ReferenceType = 0x10,
    CompileUnit = 0x11,
    StringType = 0x12,
    StructureType = 0x13,
    SubroutineType = 0x15,
    Typedef = 0x16,
    UnionType = 0x17,
    UnspecifiedParameters = 0x18,
    Variant = 0x19,
    CommonBlock = 0x1A,
    CommonInclusion = 0x1B,
    Inheritance = 0x1C,
    InlinedSubroutine = 0x1D,
    Module = 0x1E,
    PtrToMemberType = 0x1F,
    SetType = 0x20,
    SubrangeType = 0x21,
    WithStmt = 0x22,
    AccessDeclaration = 0x23,
    BaseType = 0x24,
    CatchBlock = 0x25,
    ConstType = 0x26,
    Constant = 0x27,
    Enumerator = 0x28,
    FileType = 0x29,
    Friend = 0x2A,
    Namelist = 0x2B,
    NamelistItem = 0x2C,
    PackedType = 0x2D,
    Subprogram = 0x2E,
    TemplateTypeParameter = 0x2F,
    TemplateValueParameter = 0x30,
    ThrownType = 0x31,
    TryBlock = 0x32,
    VariantPart = 0x33,
    Variable = 0x34,
    VolatileType = 0x35,
    // DWARF 3
    DwarfProcedure = 0x36,
    RestrictType = 0x37,
    InterfaceType = 0x38,
    Namespace = 0x39,
    ImportedModule = 0x3A,
    UnspecifiedType = 0x3B,
    PartialUnit = 0x3C,
    ImportedUnit = 0x3D,
    Condition = 0x3F,
    SharedType = 0x40,
    // DWARF 4
    TypeUnit = 0x41,
    RvalueReferenceType = 0x42,
    TemplateAlias = 0x43,
    // DWARF 5
    CoarrayType = 0x44,
    GenericSubrange = 0x45,
    DynamicType = 0x46,
    AtomicType = 0x47,
    CallSite = 0x48,
    CallSiteParameter = 0x49,
    SkeletonUnit = 0x4A,
    ImmutableType = 0x4B,
    Unknown(u16),
}

impl From<u16> for DwTag {
    fn from(value: u16) -> Self {
        match value {
            0x01 => DwTag::ArrayType,
            0x02 => DwTag::ClassType,
            0x03 => DwTag::EntryPoint,
            0x04 => DwTag::EnumerationType,
            0x05 => DwTag::FormalParameter,
            0x08 => DwTag::ImportedDeclaration,
            0x0A => DwTag::Label,
            0x0B => DwTag::LexicalBlock,
            0x0D => DwTag::Member,
            0x0F => DwTag::PointerType,
            0x10 => DwTag::ReferenceType,
            0x11 => DwTag::CompileUnit,
            0x12 => DwTag::StringType,
            0x13 => DwTag::StructureType,
            0x15 => DwTag::SubroutineType,
            0x16 => DwTag::Typedef,
            0x17 => DwTag::UnionType,
            0x18 => DwTag::UnspecifiedParameters,
            0x19 => DwTag::Variant,
            0x1A => DwTag::CommonBlock,
            0x1B => DwTag::CommonInclusion,
            0x1C => DwTag::Inheritance,
            0x1D => DwTag::InlinedSubroutine,
            0x1E => DwTag::Module,
            0x1F => DwTag::PtrToMemberType,
            0x20 => DwTag::SetType,
            0x21 => DwTag::SubrangeType,
            0x22 => DwTag::WithStmt,
            0x23 => DwTag::AccessDeclaration,
            0x24 => DwTag::BaseType,
            0x25 => DwTag::CatchBlock,
            0x26 => DwTag::ConstType,
            0x27 => DwTag::Constant,
            0x28 => DwTag::Enumerator,
            0x29 => DwTag::FileType,
            0x2A => DwTag::Friend,
            0x2B => DwTag::Namelist,
            0x2C => DwTag::NamelistItem,
            0x2D => DwTag::PackedType,
            0x2E => DwTag::Subprogram,
            0x2F => DwTag::TemplateTypeParameter,
            0x30 => DwTag::TemplateValueParameter,
            0x31 => DwTag::ThrownType,
            0x32 => DwTag::TryBlock,
            0x33 => DwTag::VariantPart,
            0x34 => DwTag::Variable,
            0x35 => DwTag::VolatileType,
            0x36 => DwTag::DwarfProcedure,
            0x37 => DwTag::RestrictType,
            0x38 => DwTag::InterfaceType,
            0x39 => DwTag::Namespace,
            0x3A => DwTag::ImportedModule,
            0x3B => DwTag::UnspecifiedType,
            0x3C => DwTag::PartialUnit,
            0x3D => DwTag::ImportedUnit,
            0x3F => DwTag::Condition,
            0x40 => DwTag::SharedType,
            0x41 => DwTag::TypeUnit,
            0x42 => DwTag::RvalueReferenceType,
            0x43 => DwTag::TemplateAlias,
            0x44 => DwTag::CoarrayType,
            0x45 => DwTag::GenericSubrange,
            0x46 => DwTag::DynamicType,
            0x47 => DwTag::AtomicType,
            0x48 => DwTag::CallSite,
            0x49 => DwTag::CallSiteParameter,
            0x4A => DwTag::SkeletonUnit,
            0x4B => DwTag::ImmutableType,
            _ => DwTag::Unknown(value),
        }
    }
}

/// DWARF attribute values (DW_AT_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum DwAt {
    Sibling = 0x01,
    Location = 0x02,
    Name = 0x03,
    Ordering = 0x09,
    ByteSize = 0x0B,
    BitOffset = 0x0C,
    BitSize = 0x0D,
    StmtList = 0x10,
    LowPc = 0x11,
    HighPc = 0x12,
    Language = 0x13,
    Discr = 0x15,
    DiscrValue = 0x16,
    Visibility = 0x17,
    Import = 0x18,
    StringLength = 0x19,
    CommonReference = 0x1A,
    CompDir = 0x1B,
    ConstValue = 0x1C,
    ContainingType = 0x1D,
    DefaultValue = 0x1E,
    Inline = 0x20,
    IsOptional = 0x21,
    LowerBound = 0x22,
    Producer = 0x25,
    Prototyped = 0x27,
    ReturnAddr = 0x2A,
    StartScope = 0x2C,
    BitStride = 0x2E,
    UpperBound = 0x2F,
    AbstractOrigin = 0x31,
    Accessibility = 0x32,
    AddressClass = 0x33,
    Artificial = 0x34,
    BaseTypes = 0x35,
    CallingConvention = 0x36,
    Count = 0x37,
    DataMemberLocation = 0x38,
    DeclColumn = 0x39,
    DeclFile = 0x3A,
    DeclLine = 0x3B,
    Declaration = 0x3C,
    DiscrList = 0x3D,
    Encoding = 0x3E,
    External = 0x3F,
    FrameBase = 0x40,
    Friend = 0x41,
    IdentifierCase = 0x42,
    MacroInfo = 0x43,
    NamelistItem = 0x44,
    Priority = 0x45,
    Segment = 0x46,
    Specification = 0x47,
    StaticLink = 0x48,
    Type = 0x49,
    UseLocation = 0x4A,
    VariableParameter = 0x4B,
    Virtuality = 0x4C,
    VtableElemLocation = 0x4D,
    // DWARF 3
    Allocated = 0x4E,
    Associated = 0x4F,
    DataLocation = 0x50,
    ByteStride = 0x51,
    EntryPc = 0x52,
    UseUtf8 = 0x53,
    Extension = 0x54,
    Ranges = 0x55,
    Trampoline = 0x56,
    CallColumn = 0x57,
    CallFile = 0x58,
    CallLine = 0x59,
    Description = 0x5A,
    BinaryScale = 0x5B,
    DecimalScale = 0x5C,
    Small = 0x5D,
    DecimalSign = 0x5E,
    DigitCount = 0x5F,
    PictureString = 0x60,
    Mutable = 0x61,
    ThreadsScaled = 0x62,
    Explicit = 0x63,
    ObjectPointer = 0x64,
    Endianity = 0x65,
    Elemental = 0x66,
    Pure = 0x67,
    Recursive = 0x68,
    // DWARF 4
    Signature = 0x69,
    MainSubprogram = 0x6A,
    DataBitOffset = 0x6B,
    ConstExpr = 0x6C,
    EnumClass = 0x6D,
    LinkageName = 0x6E,
    // DWARF 5
    StringLengthBitSize = 0x6F,
    StringLengthByteSize = 0x70,
    Rank = 0x71,
    StrOffsetsBase = 0x72,
    AddrBase = 0x73,
    RnglistsBase = 0x74,
    DwoName = 0x76,
    Reference = 0x77,
    RvalueReference = 0x78,
    Macros = 0x79,
    CallAllCalls = 0x7A,
    CallAllSourceCalls = 0x7B,
    CallAllTailCalls = 0x7C,
    CallReturnPc = 0x7D,
    CallValue = 0x7E,
    CallOrigin = 0x7F,
    CallParameter = 0x80,
    CallPc = 0x81,
    CallTailCall = 0x82,
    CallTarget = 0x83,
    CallTargetClobbered = 0x84,
    CallDataLocation = 0x85,
    CallDataValue = 0x86,
    Noreturn = 0x87,
    Alignment = 0x88,
    ExportSymbols = 0x89,
    Deleted = 0x8A,
    Defaulted = 0x8B,
    LoclistsBase = 0x8C,
    Unknown(u16),
}

impl From<u16> for DwAt {
    fn from(value: u16) -> Self {
        match value {
            0x01 => DwAt::Sibling,
            0x02 => DwAt::Location,
            0x03 => DwAt::Name,
            0x09 => DwAt::Ordering,
            0x0B => DwAt::ByteSize,
            0x0C => DwAt::BitOffset,
            0x0D => DwAt::BitSize,
            0x10 => DwAt::StmtList,
            0x11 => DwAt::LowPc,
            0x12 => DwAt::HighPc,
            0x13 => DwAt::Language,
            0x15 => DwAt::Discr,
            0x16 => DwAt::DiscrValue,
            0x17 => DwAt::Visibility,
            0x18 => DwAt::Import,
            0x19 => DwAt::StringLength,
            0x1A => DwAt::CommonReference,
            0x1B => DwAt::CompDir,
            0x1C => DwAt::ConstValue,
            0x1D => DwAt::ContainingType,
            0x1E => DwAt::DefaultValue,
            0x20 => DwAt::Inline,
            0x21 => DwAt::IsOptional,
            0x22 => DwAt::LowerBound,
            0x25 => DwAt::Producer,
            0x27 => DwAt::Prototyped,
            0x2A => DwAt::ReturnAddr,
            0x2C => DwAt::StartScope,
            0x2E => DwAt::BitStride,
            0x2F => DwAt::UpperBound,
            0x31 => DwAt::AbstractOrigin,
            0x32 => DwAt::Accessibility,
            0x33 => DwAt::AddressClass,
            0x34 => DwAt::Artificial,
            0x35 => DwAt::BaseTypes,
            0x36 => DwAt::CallingConvention,
            0x37 => DwAt::Count,
            0x38 => DwAt::DataMemberLocation,
            0x39 => DwAt::DeclColumn,
            0x3A => DwAt::DeclFile,
            0x3B => DwAt::DeclLine,
            0x3C => DwAt::Declaration,
            0x3D => DwAt::DiscrList,
            0x3E => DwAt::Encoding,
            0x3F => DwAt::External,
            0x40 => DwAt::FrameBase,
            0x41 => DwAt::Friend,
            0x42 => DwAt::IdentifierCase,
            0x43 => DwAt::MacroInfo,
            0x44 => DwAt::NamelistItem,
            0x45 => DwAt::Priority,
            0x46 => DwAt::Segment,
            0x47 => DwAt::Specification,
            0x48 => DwAt::StaticLink,
            0x49 => DwAt::Type,
            0x4A => DwAt::UseLocation,
            0x4B => DwAt::VariableParameter,
            0x4C => DwAt::Virtuality,
            0x4D => DwAt::VtableElemLocation,
            0x4E => DwAt::Allocated,
            0x4F => DwAt::Associated,
            0x50 => DwAt::DataLocation,
            0x51 => DwAt::ByteStride,
            0x52 => DwAt::EntryPc,
            0x53 => DwAt::UseUtf8,
            0x54 => DwAt::Extension,
            0x55 => DwAt::Ranges,
            0x56 => DwAt::Trampoline,
            0x57 => DwAt::CallColumn,
            0x58 => DwAt::CallFile,
            0x59 => DwAt::CallLine,
            0x5A => DwAt::Description,
            0x5B => DwAt::BinaryScale,
            0x5C => DwAt::DecimalScale,
            0x5D => DwAt::Small,
            0x5E => DwAt::DecimalSign,
            0x5F => DwAt::DigitCount,
            0x60 => DwAt::PictureString,
            0x61 => DwAt::Mutable,
            0x62 => DwAt::ThreadsScaled,
            0x63 => DwAt::Explicit,
            0x64 => DwAt::ObjectPointer,
            0x65 => DwAt::Endianity,
            0x66 => DwAt::Elemental,
            0x67 => DwAt::Pure,
            0x68 => DwAt::Recursive,
            0x69 => DwAt::Signature,
            0x6A => DwAt::MainSubprogram,
            0x6B => DwAt::DataBitOffset,
            0x6C => DwAt::ConstExpr,
            0x6D => DwAt::EnumClass,
            0x6E => DwAt::LinkageName,
            0x6F => DwAt::StringLengthBitSize,
            0x70 => DwAt::StringLengthByteSize,
            0x71 => DwAt::Rank,
            0x72 => DwAt::StrOffsetsBase,
            0x73 => DwAt::AddrBase,
            0x74 => DwAt::RnglistsBase,
            0x76 => DwAt::DwoName,
            0x77 => DwAt::Reference,
            0x78 => DwAt::RvalueReference,
            0x79 => DwAt::Macros,
            0x7A => DwAt::CallAllCalls,
            0x7B => DwAt::CallAllSourceCalls,
            0x7C => DwAt::CallAllTailCalls,
            0x7D => DwAt::CallReturnPc,
            0x7E => DwAt::CallValue,
            0x7F => DwAt::CallOrigin,
            0x80 => DwAt::CallParameter,
            0x81 => DwAt::CallPc,
            0x82 => DwAt::CallTailCall,
            0x83 => DwAt::CallTarget,
            0x84 => DwAt::CallTargetClobbered,
            0x85 => DwAt::CallDataLocation,
            0x86 => DwAt::CallDataValue,
            0x87 => DwAt::Noreturn,
            0x88 => DwAt::Alignment,
            0x89 => DwAt::ExportSymbols,
            0x8A => DwAt::Deleted,
            0x8B => DwAt::Defaulted,
            0x8C => DwAt::LoclistsBase,
            _ => DwAt::Unknown(value),
        }
    }
}

/// DWARF form values (DW_FORM_*).
/// These specify how attribute values are encoded.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum DwForm {
    Addr = 0x01,
    Block2 = 0x03,
    Block4 = 0x04,
    Data2 = 0x05,
    Data4 = 0x06,
    Data8 = 0x07,
    String = 0x08,
    Block = 0x09,
    Block1 = 0x0A,
    Data1 = 0x0B,
    Flag = 0x0C,
    Sdata = 0x0D,
    Strp = 0x0E,
    Udata = 0x0F,
    RefAddr = 0x10,
    Ref1 = 0x11,
    Ref2 = 0x12,
    Ref4 = 0x13,
    Ref8 = 0x14,
    RefUdata = 0x15,
    Indirect = 0x16,
    // DWARF 4
    SecOffset = 0x17,
    Exprloc = 0x18,
    FlagPresent = 0x19,
    RefSig8 = 0x20,
    // DWARF 5
    Strx = 0x1A,
    Addrx = 0x1B,
    RefSup4 = 0x1C,
    StrpSup = 0x1D,
    Data16 = 0x1E,
    LineStrp = 0x1F,
    ImplicitConst = 0x21,
    Loclistx = 0x22,
    Rnglistx = 0x23,
    RefSup8 = 0x24,
    Strx1 = 0x25,
    Strx2 = 0x26,
    Strx3 = 0x27,
    Strx4 = 0x28,
    Addrx1 = 0x29,
    Addrx2 = 0x2A,
    Addrx3 = 0x2B,
    Addrx4 = 0x2C,
    Unknown(u8),
}

impl From<u8> for DwForm {
    fn from(value: u8) -> Self {
        match value {
            0x01 => DwForm::Addr,
            0x03 => DwForm::Block2,
            0x04 => DwForm::Block4,
            0x05 => DwForm::Data2,
            0x06 => DwForm::Data4,
            0x07 => DwForm::Data8,
            0x08 => DwForm::String,
            0x09 => DwForm::Block,
            0x0A => DwForm::Block1,
            0x0B => DwForm::Data1,
            0x0C => DwForm::Flag,
            0x0D => DwForm::Sdata,
            0x0E => DwForm::Strp,
            0x0F => DwForm::Udata,
            0x10 => DwForm::RefAddr,
            0x11 => DwForm::Ref1,
            0x12 => DwForm::Ref2,
            0x13 => DwForm::Ref4,
            0x14 => DwForm::Ref8,
            0x15 => DwForm::RefUdata,
            0x16 => DwForm::Indirect,
            0x17 => DwForm::SecOffset,
            0x18 => DwForm::Exprloc,
            0x19 => DwForm::FlagPresent,
            0x1A => DwForm::Strx,
            0x1B => DwForm::Addrx,
            0x1C => DwForm::RefSup4,
            0x1D => DwForm::StrpSup,
            0x1E => DwForm::Data16,
            0x1F => DwForm::LineStrp,
            0x20 => DwForm::RefSig8,
            0x21 => DwForm::ImplicitConst,
            0x22 => DwForm::Loclistx,
            0x23 => DwForm::Rnglistx,
            0x24 => DwForm::RefSup8,
            0x25 => DwForm::Strx1,
            0x26 => DwForm::Strx2,
            0x27 => DwForm::Strx3,
            0x28 => DwForm::Strx4,
            0x29 => DwForm::Addrx1,
            0x2A => DwForm::Addrx2,
            0x2B => DwForm::Addrx3,
            0x2C => DwForm::Addrx4,
            _ => DwForm::Unknown(value),
        }
    }
}

/// Base type encodings (DW_ATE_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum DwAte {
    Address = 0x01,
    Boolean = 0x02,
    ComplexFloat = 0x03,
    Float = 0x04,
    Signed = 0x05,
    SignedChar = 0x06,
    Unsigned = 0x07,
    UnsignedChar = 0x08,
    ImaginaryFloat = 0x09,
    PackedDecimal = 0x0A,
    NumericString = 0x0B,
    Edited = 0x0C,
    SignedFixed = 0x0D,
    UnsignedFixed = 0x0E,
    DecimalFloat = 0x0F,
    Utf = 0x10,
    Ucs = 0x11,
    Ascii = 0x12,
    Unknown(u8),
}

impl From<u8> for DwAte {
    fn from(value: u8) -> Self {
        match value {
            0x01 => DwAte::Address,
            0x02 => DwAte::Boolean,
            0x03 => DwAte::ComplexFloat,
            0x04 => DwAte::Float,
            0x05 => DwAte::Signed,
            0x06 => DwAte::SignedChar,
            0x07 => DwAte::Unsigned,
            0x08 => DwAte::UnsignedChar,
            0x09 => DwAte::ImaginaryFloat,
            0x0A => DwAte::PackedDecimal,
            0x0B => DwAte::NumericString,
            0x0C => DwAte::Edited,
            0x0D => DwAte::SignedFixed,
            0x0E => DwAte::UnsignedFixed,
            0x0F => DwAte::DecimalFloat,
            0x10 => DwAte::Utf,
            0x11 => DwAte::Ucs,
            0x12 => DwAte::Ascii,
            _ => DwAte::Unknown(value),
        }
    }
}

/// Source languages (DW_LANG_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum DwLang {
    C89 = 0x0001,
    C = 0x0002,
    Ada83 = 0x0003,
    CPlusPlus = 0x0004,
    Cobol74 = 0x0005,
    Cobol85 = 0x0006,
    Fortran77 = 0x0007,
    Fortran90 = 0x0008,
    Pascal83 = 0x0009,
    Modula2 = 0x000A,
    Java = 0x000B,
    C99 = 0x000C,
    Ada95 = 0x000D,
    Fortran95 = 0x000E,
    Pli = 0x000F,
    ObjC = 0x0010,
    ObjCPlusPlus = 0x0011,
    Upc = 0x0012,
    D = 0x0013,
    Python = 0x0014,
    // DWARF 5
    OpenCl = 0x0015,
    Go = 0x0016,
    Modula3 = 0x0017,
    Haskell = 0x0018,
    CPlusPlus03 = 0x0019,
    CPlusPlus11 = 0x001A,
    OclC = 0x001B,
    Rust = 0x001C,
    C11 = 0x001D,
    Swift = 0x001E,
    Julia = 0x001F,
    Dylan = 0x0020,
    CPlusPlus14 = 0x0021,
    Fortran03 = 0x0022,
    Fortran08 = 0x0023,
    RenderScript = 0x0024,
    Bliss = 0x0025,
    Kotlin = 0x0026,
    Zig = 0x0027,
    Crystal = 0x0028,
    CPlusPlus17 = 0x002A,
    CPlusPlus20 = 0x002B,
    C17 = 0x002C,
    Fortran18 = 0x002D,
    Ada2005 = 0x002E,
    Ada2012 = 0x002F,
    Unknown(u16),
}

impl From<u16> for DwLang {
    fn from(value: u16) -> Self {
        match value {
            0x0001 => DwLang::C89,
            0x0002 => DwLang::C,
            0x0003 => DwLang::Ada83,
            0x0004 => DwLang::CPlusPlus,
            0x0005 => DwLang::Cobol74,
            0x0006 => DwLang::Cobol85,
            0x0007 => DwLang::Fortran77,
            0x0008 => DwLang::Fortran90,
            0x0009 => DwLang::Pascal83,
            0x000A => DwLang::Modula2,
            0x000B => DwLang::Java,
            0x000C => DwLang::C99,
            0x000D => DwLang::Ada95,
            0x000E => DwLang::Fortran95,
            0x000F => DwLang::Pli,
            0x0010 => DwLang::ObjC,
            0x0011 => DwLang::ObjCPlusPlus,
            0x0012 => DwLang::Upc,
            0x0013 => DwLang::D,
            0x0014 => DwLang::Python,
            0x0015 => DwLang::OpenCl,
            0x0016 => DwLang::Go,
            0x0017 => DwLang::Modula3,
            0x0018 => DwLang::Haskell,
            0x0019 => DwLang::CPlusPlus03,
            0x001A => DwLang::CPlusPlus11,
            0x001B => DwLang::OclC,
            0x001C => DwLang::Rust,
            0x001D => DwLang::C11,
            0x001E => DwLang::Swift,
            0x001F => DwLang::Julia,
            0x0020 => DwLang::Dylan,
            0x0021 => DwLang::CPlusPlus14,
            0x0022 => DwLang::Fortran03,
            0x0023 => DwLang::Fortran08,
            0x0024 => DwLang::RenderScript,
            0x0025 => DwLang::Bliss,
            0x0026 => DwLang::Kotlin,
            0x0027 => DwLang::Zig,
            0x0028 => DwLang::Crystal,
            0x002A => DwLang::CPlusPlus17,
            0x002B => DwLang::CPlusPlus20,
            0x002C => DwLang::C17,
            0x002D => DwLang::Fortran18,
            0x002E => DwLang::Ada2005,
            0x002F => DwLang::Ada2012,
            _ => DwLang::Unknown(value),
        }
    }
}

/// Line number program opcodes (DW_LNS_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum DwLns {
    Copy = 0x01,
    AdvancePc = 0x02,
    AdvanceLine = 0x03,
    SetFile = 0x04,
    SetColumn = 0x05,
    NegateStmt = 0x06,
    SetBasicBlock = 0x07,
    ConstAddPc = 0x08,
    FixedAdvancePc = 0x09,
    // DWARF 3
    SetPrologueEnd = 0x0A,
    SetEpilogueBegin = 0x0B,
    SetIsa = 0x0C,
}

/// Extended line number program opcodes (DW_LNE_*).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum DwLne {
    EndSequence = 0x01,
    SetAddress = 0x02,
    DefineFile = 0x03,
    // DWARF 4
    SetDiscriminator = 0x04,
}
